# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.IntegerField(default=50),
        ),
    ]
