# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20180411_1609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bus_trip',
            table='Bus_trip',
        ),
    ]
