# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookAticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'CNL', b'Cancelled'), (b'CNF', b'Confirmed')], default=b'CNF', max_length=2)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('A_time', models.TimeField()),
                ('D_time', models.TimeField()),
                ('A_from', models.CharField(default=b'A', max_length=100)),
                ('D_at', models.CharField(default=b'A', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bus_number', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('booking_seats_num', models.IntegerField(default=1)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Booked Tickets',
            },
        ),
    ]
